version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo_db
    ports:
      - "9000:9000"
  mongo_db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: "mongo:5.0.0"
    restart: always
    ports:
      - "27017:27017"