funda:
  url: https://www.funda.nl/

pararius:
  url: https://www.pararius.nl

spring:
  data:
    mongodb:
      database: wew_lad
      port: 27017
      host: mongo_db
      username: user
      password: password
  security:
    user:
      name: hank
      password: hank
server:
  port: 9000